Fixed a game logic bug
error: NullReferenceException: Object reference not set to an instance of an object
GameLogic.Update () (at Assets/Scripts/Game/GameLogic.cs:97)

Added a boolean to check if the initialization (start function) is complete before running the update function.

That way, currentPinGroupStopChecker is assigned a value before being called